version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    container_name: landing-service
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
          
  # Add more services below
  add-service:
    build: ./Add  # path is relative to docker-compose.yml location
    container_name: add-service
    hostname: add-service
    networks:
      sample:
        aliases:
          - add-service

   # Add more services below
  sub-service:
    build: ./Sub  # path is relative to docker-compose.yml location
    container_name: sub-service
    hostname: sub-service
    networks:
      sample:
        aliases:
          - sub-service

  # Add more services below
  mul-service:
    build: ./Mul  # path is relative to docker-compose.yml location
    container_name: mul-service
    hostname: mul-service
    networks:
      sample:
        aliases:
          - mul-service

  # Add more services below
  div-service:
    build: ./Div  # path is relative to docker-compose.yml location
    container_name: div-service
    hostname: div-service
    networks:
      sample:
        aliases:
          - div-service
  
  
  equal-service:
    build: ./Equal  # path is relative to docker-compose.yml location
    container_name: equal-service
    hostname: equal-service
    networks:
      sample:
        aliases:
          - equal-service
    
  modulus-service:
    build: ./Modulus  # path is relative to docker-compose.yml location
    container_name: modulus-service
    hostname: modulus-service
    networks:
      sample:
        aliases:
          - modulus-service
    
  exponent-service:
    build: ./Exponent  # path is relative to docker-compose.yml location
    container_name: exponent-service
    hostname: exponent-service
    networks:
      sample:
        aliases:
          - exponent-service
          
networks:
  sample:
